# Generated by Django 6.0.3 on 2026-03-21 01:33

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name="movie",
            constraint=models.UniqueConstraint(
                fields=("title", "release_date"), name="unique_movie_title_release_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        models.Func(
                            models.F("start_time"),
                            models.F("end_time"),
                            function="TSTZRANGE",
                            output_field=django.contrib.postgres.fields.ranges.DateTimeRangeField(),
                        ),
                        "&&",
                    ),
                    ("room", "="),
                ],
                name="exclude_overlapping_sessions_per_room",
            ),
        ),
    ]
