# Generated by Django 6.0.3 on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_movie_unique_movie_title_release_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_cartaz", "Em cartaz"),
                    ("pre_venda", "Pre-venda"),
                ],
                default="em_cartaz",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
