# Generated by Django 6.0.3 on 2026-05-14

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_movie_status_movie_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("30.00"),
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gt", 0)),
                name="session_base_price_gt_0",
            ),
        ),
    ]
