# Generated by Django 6.0.3 on 2026-05-14

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


LEGACY_SESSION_BASE_PRICE = Decimal("30.00")


def backfill_legacy_session_base_price(apps, schema_editor):
    Session = apps.get_model("catalog", "Session")

    # Existing sessions predate pricing support. This explicit legacy backfill
    # keeps the migration non-interactive while making the chosen value visible
    # for operators to review and update after deployment when needed.
    Session.objects.filter(base_price__isnull=True).update(
        base_price=LEGACY_SESSION_BASE_PRICE
    )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_movie_status_movie_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.RunPython(
            backfill_legacy_session_base_price,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="session",
            name="base_price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gt", 0)),
                name="session_base_price_gt_0",
            ),
        ),
    ]
