# Generated by Django 6.0.3 on 2026-03-21 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_movie_unique_movie_title_release_date_and_more"),
        ("reservations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionSeat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("PURCHASED", "Purchased"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("lock_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "locked_by_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_session_seats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_seats",
                        to="reservations.seat",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_seats",
                        to="catalog.session",
                    ),
                ),
            ],
            options={
                "db_table": "reservation_session_seats",
                "ordering": ["session", "seat__row", "seat__number"],
                "indexes": [
                    models.Index(
                        fields=["session", "status"], name="session_status_idx"
                    ),
                    models.Index(
                        fields=["session", "lock_expires_at"],
                        name="session_lock_expires_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "seat"), name="unique_seat_per_session"
                    )
                ],
            },
        ),
    ]
