# Generated by Django 6.0.3 on 2026-03-21 15:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_movie_unique_movie_title_release_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row", models.CharField(max_length=10)),
                ("number", models.PositiveIntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="catalog.room",
                    ),
                ),
            ],
            options={
                "db_table": "reservation_seats",
                "ordering": ["room", "row", "number"],
                "indexes": [models.Index(fields=["room"], name="seat_room_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("room", "row", "number"),
                        name="unique_seat_per_room_position",
                    )
                ],
            },
        ),
    ]
