# Generated by Django 6.0.3 on 2026-03-21 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


def migrate_seat_rows(apps, schema_editor):
    Seat = apps.get_model("reservations", "Seat")
    SeatRow = apps.get_model("reservations", "SeatRow")

    for seat in Seat.objects.all().iterator():
        normalized_row_name = seat.row.strip().upper()

        seat_row, _ = SeatRow.objects.get_or_create(
            room_id=seat.room_id,
            name=normalized_row_name,
        )

        seat.seat_row_id = seat_row.id
        seat.save(update_fields=["seat_row"])


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_movie_unique_movie_title_release_date_and_more"),
        ("reservations", "0002_sessionseat"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeatRow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_rows",
                        to="catalog.room",
                    ),
                ),
            ],
            options={
                "db_table": "reservation_seat_rows",
                "ordering": ["room", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="seatrow",
            index=models.Index(fields=["room"], name="seat_row_room_idx"),
        ),
        migrations.AddConstraint(
            model_name="seatrow",
            constraint=models.UniqueConstraint(
                fields=("room", "name"),
                name="unique_seat_row_per_room",
            ),
        ),
        migrations.AlterModelOptions(
            name="seat",
            options={"ordering": ["row", "number"]},
        ),
        migrations.AlterModelOptions(
            name="sessionseat",
            options={"ordering": ["session", "seat__row__name", "seat__number"]},
        ),
        migrations.RemoveConstraint(
            model_name="seat",
            name="unique_seat_per_room_position",
        ),
        migrations.RemoveIndex(
            model_name="seat",
            name="seat_room_idx",
        ),
        migrations.AddField(
            model_name="seat",
            name="seat_row",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_seats_temp",
                to="reservations.seatrow",
            ),
        ),
        migrations.RunPython(migrate_seat_rows, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="seat",
            name="row",
        ),
        migrations.RenameField(
            model_name="seat",
            old_name="seat_row",
            new_name="row",
        ),
        migrations.AlterField(
            model_name="seat",
            name="row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seats",
                to="reservations.seatrow",
            ),
        ),
        migrations.RemoveField(
            model_name="seat",
            name="room",
        ),
        migrations.AddIndex(
            model_name="seat",
            index=models.Index(fields=["row"], name="seat_row_idx"),
        ),
        migrations.AddConstraint(
            model_name="seat",
            constraint=models.UniqueConstraint(
                fields=("row", "number"),
                name="unique_seat_number_per_row",
            ),
        ),
    ]