# Generated by Django 6.0.3 on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0004_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="seat",
            name="is_accessible",
            field=models.BooleanField(default=False),
        ),
    ]
