# Generated by Codex on 2026-05-19

import decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_seat_is_accessible"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[("inteira", "Inteira"), ("meia", "Meia")],
                default="inteira",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cartao_credito", "Cartao de credito"),
                    ("pix", "PIX"),
                ],
                default="pix",
                max_length=20,
            ),
        ),
    ]
