# Generated by Codex on 2026-05-19

import decimal

from django.db import migrations, models


def backfill_legacy_ticket_purchase_data(apps, schema_editor):
    Ticket = apps.get_model("reservations", "Ticket")

    legacy_tickets = Ticket.objects.select_related(
        "session_seat__session",
    ).filter(amount_paid=decimal.Decimal("0.00"))

    for ticket in legacy_tickets.iterator():
        ticket.amount_paid = ticket.session_seat.session.base_price
        ticket.save(update_fields=["amount_paid"])


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0005_seat_is_accessible"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[("inteira", "Inteira"), ("meia", "Meia")],
                default="inteira",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                max_digits=8,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cartao_credito", "Cartao de credito"),
                    ("pix", "PIX"),
                ],
                default="pix",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            code=backfill_legacy_ticket_purchase_data,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
